server:
  run_mode: debug
  http_port: :9000
  read_timeout: 60
  write_timeout: 60
app:
  default_page_size: 10
  max_page_size: 100
  log_save_path: storage/log
  log_file_name: test.log
  upload_save_path: storage/uploads
  upload_server_url: http://127.0.0.1:9000/file
  upload_image_max_size: 5 # MB
  upload_image_allow_exts:
    - .jpg
    - .jpeg
    - .png
database:
  username: root # 填写你的数据库账号
  password: 12345678 # 填写你的数据库密码
  host: 127.0.0.1:3306
  db_name: express_blog

jwt:
  secret: blog-demo
  issuer: blog-demo
  expire: 6 # hours
